### ISSUE TITLE
Not secure

### ISSUE THREAD

**Issue by omerbaldo** [robneal/Hackerspace#1]
doesn't contain cross site verification tokens or captcha. can easily be hacked or ddosed.

**Comment by robneal** [comment]
Don't have any forms or input fields on this sit shouldn't that prevent XSS. If not and I missed something how can I fix it?

**Comment by omerbaldo** [comment]
Your XSS is written wrong. Look at this documentation which should fix your problem

http://4.bp.blogspot.com/-pPLoyosI_Zo/VJ12aP5QpyI/AAAAAAAADCY/XZvWpC0xc4E/s1600/banana-gif.gif
